server:
  port: 8080

spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 3000

    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        min-idle: 0
        max-idle: 8

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 123456
#    url: jdbc:mysql://localhost:3306/glt_1?characterEncoding=utf8
#    type: com.alibaba.druid.pool.DruidDataSource

glt:
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/glt_1?characterEncoding=utf8
    slave_1:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/glt_1?characterEncoding=utf8
    slave_2:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/glt_1?characterEncoding=utf8